#!/usr/bin/env python3
"""Build a compact HashRes entry map from an authorized APK ZIP.

For each assets/HashRes/* member, record the absolute data offset range inside
the APK so runtime tracers can map mmap/pread hits back to a logical path.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import struct
import sys
import zipfile


LOCAL_HEADER = struct.Struct("<IHHHHHIIIHH")


def map_apk(apk: Path) -> dict[str, object]:
    entries: list[dict[str, object]] = []
    with apk.open("rb") as handle, zipfile.ZipFile(apk) as archive:
        for info in archive.infolist():
            if "HashRes" not in info.filename:
                continue
            handle.seek(info.header_offset)
            header = handle.read(LOCAL_HEADER.size)
            if len(header) != LOCAL_HEADER.size:
                raise ValueError(f"truncated local header at {info.header_offset}")
            (
                signature,
                _version,
                flags,
                method,
                _time,
                _date,
                _crc,
                local_compress_size,
                local_file_size,
                name_length,
                extra_length,
            ) = LOCAL_HEADER.unpack(header)
            if signature != 0x04034B50:
                raise ValueError(f"bad local signature at {info.header_offset:#x}")
            # Prefer central-directory sizes. Local headers often leave size fields
            # at 0 when the data-descriptor flag (bit 3) is set (common for DEFLATE).
            compress_size = int(info.compress_size)
            file_size = int(info.file_size)
            if compress_size <= 0 and local_compress_size > 0:
                compress_size = local_compress_size
            if file_size <= 0 and local_file_size > 0:
                file_size = local_file_size
            data_offset = info.header_offset + LOCAL_HEADER.size + name_length + extra_length
            entries.append(
                {
                    "name": info.filename,
                    "method": int(info.compress_type if info.compress_type is not None else method),
                    "compress_size": compress_size,
                    "file_size": file_size,
                    "header_offset": info.header_offset,
                    "data_offset": data_offset,
                    "data_end": data_offset + compress_size,
                    "local_flags": flags,
                    "local_compress_size": local_compress_size,
                    "local_file_size": local_file_size,
                }
            )
    entries.sort(key=lambda item: int(item["data_offset"]))
    return {"count": len(entries), "entries": entries}


def emit_js(payload: dict[str, object]) -> str:
    compact = [
        [
            int(item["data_offset"]),
            int(item["data_end"]),
            str(item["name"]),
            int(item["method"]),
            int(item["file_size"]),
        ]
        for item in payload["entries"]  # type: ignore[index]
    ]
    return (
        "/* Generated by kktkky_apk_hashres_map.py — do not edit. */\n"
        "'use strict';\n"
        f"var HASHRES_APK_MAP = {json.dumps(compact, separators=(',', ':'))};\n"
    )


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("apk", type=Path)
    result.add_argument("--json-out", type=Path)
    result.add_argument("--js-out", type=Path)
    return result


def main() -> int:
    args = parser().parse_args()
    payload = map_apk(args.apk.resolve())
    if args.json_out is None and args.js_out is None:
        json.dump(payload, sys.stdout, ensure_ascii=False, indent=2)
        print()
        return 0
    if args.json_out is not None:
        args.json_out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    if args.js_out is not None:
        args.js_out.write_text(emit_js(payload))
    print(
        f"hashres_entries={payload['count']} "
        f"json={args.json_out or '-'} js={args.js_out or '-'}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
